### PR TITLE
Fix crash when requesting enclosing ranges of out-of-bounds range from a RangeSet

### PR DESCRIPTION
**Pull request by rgabbard**

### CODE REVIEW

**Comment by ConstantineLignos** [comment]
I'll let @boschee do all review on this.

**Comment by rgabbard** [comment]
@ConstantineLignos : you might want to review just the Makefile changes to get the exit statuses to come out right

**Comment by ConstantineLignos** [comment]
Makefile changes look good.

**Comment by rgabbard** [comment]
@boschee confirms this fix works

**Pull request merged**
