### PR TITLE
closes #54

### LINKED ISSUE #54: _FileCharSource should specify UTF-8 encoding when opening the file

### PR DESCRIPTION
**Pull request by qpwo**
A one-line change which resolves #54 .

### CODE REVIEW

**Comment by berquist** [comment]
There is a merge conflict. Can you rebase your branch on top of the current master?

**Comment by qpwo** [comment]
Did I rebase right?

**Comment by berquist** [comment]
Something weird happened, your first commit is appearing twice (aside from a different hash). Did you do
```bash
git checkout 54-_FileCharSource-specify-UTF-8
git fetch # sometimes you need to do this if your copy of `master` is outdated
git rebase origin/master
```
or something similar? There are a few ways to do it.

(It doesn't actually matter in this case, we can squash the commits.)

**Comment by qpwo** [comment]
Hmm I don't know what caused the double commit

**Pull request merged**
