### PR TITLE
Swapped sorted_dict.iloc with SortedDict.keys(). Closes #66

### LINKED ISSUE #66: Address iLoc deprecation warning in range code
```
 /home/appveyor/projects/vistautils/vistautils/range.py:1324: DeprecationWarning: sorted_dict.iloc is deprecated. Use SortedDict.keys() instead.
    key = sorted_dict.iloc[idx - 1]
```

### PR DESCRIPTION
**Pull request by qpwo**

### CODE REVIEW

**Comment by rgabbard** [comment]
@qpwo : Can you check whether `SortedDict` does any work in `.keys()` besides just returning a field?  (to see what the performance implications of the switch are)

**Comment by qpwo** [comment]
It appears `iloc` saves the result. The `_iloc` attribute is never used anywhere else in `SortedDict`. I assume they have some reason for not saving the result in `keys()`...
```python
 @property
 def iloc(self):
     try:
         return self._iloc
     except AttributeError:
         warnings.warn(...)
         _iloc = self._iloc = SortedKeysView(self)
         return _iloc
...
def keys(self):
	return SortedKeysView(self)
```

**Comment by rgabbard** [comment]
@qpwo : Can you dig into why they deprecated `iloc`?

**Comment by qpwo** [comment]
In [Feb](https://github.com/grantjenks/python-sortedcontainers/issues/40#issuecomment-182139598) 2016 they said `iloc` looked strange. They said they wanted to get rid of it in [Dec](https://github.com/grantjenks/python-sortedcontainers/issues/59#issuecomment-265533714) 2016 because it confuses people.
They removed `iloc` in [May](https://github.com/grantjenks/python-sortedcontainers/issues/92) 2018, but that broke others' code, so they put it back as a temporary fix, and deprecated it.

I profiled the tests. This branch has `.keys()` taking `tottime=0.055` and `cumtime=0.076` with `ncalls=130327`. The master branch with `iloc` has it at `tottime=0.036` and `cumtime=0.074`, and same `ncalls`. Performance hit is not too bad. The whole test suite took 3.20 seconds, for comparison.

**Comment by rgabbard** [comment]
💯 for profiling.

**Pull request merged**
